### ISSUE TITLE
Add links to MARKET.js deployed documents to main docs page

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/docs#33]
http://docs.marketprotocol.io.s3-website-us-east-1.amazonaws.com/

add links to versions of MARKET.js documentation.

http://docs.marketprotocol.io.s3-website-us-east-1.amazonaws.com/0.4.1/

**Comment by eswarasai** [comment]
@pelsasser -- Shouldn't the versioning be like `http://docs.marketprotocol.io.s3-website-us-east-1.amazonaws.com/marketjs/0.4.1`?

**Comment by pelsasser** [comment]
yea -  we can change the folder structure in the MARKET.js deploy to accommodate those routes.

**Comment by pelsasser** [comment]
it looks like the `update-docs.js` in MARKET.js repo would need to be updated for the desired folder structure.

**Comment by pelsasser** [comment]
closing, no longer needed.
