### ISSUE TITLE
Telegram URL broken on website technical docs FAQ

### ISSUE THREAD

**Issue by BassBauman** [MARKETProtocol/docs#36]
The link 'htttps://marketprotocol.io/telegram' is broken, instead it should be 'https://marketprotocol.io/telegram' with only 2 'T's in 'https'.

The broken link can be found [here](https://docs.marketprotocol.io/#how-can-i-receive-updates-from-market-protocol).

![ink](https://user-images.githubusercontent.com/42623709/46763382-de355d00-cc96-11e8-8b88-6d3f54382958.png)

**Comment by pelsasser** [comment]
resolved and deployed
