### ISSUE TITLE
[assets] Move all the required assets to this repo

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/docs#42]
### Description

Since the `assets` repo is private now, for the images to be displayed in the `docs`, we need to move them all to this repo so that the images are displayed in the docs website

**Comment by pelsasser** [comment]
@eswarasai - I am pretty sure this was completed in the previous release, what assets are you seeing missing?

**Comment by eswarasai** [comment]
@pelsasser -- Yeah, all of them have been covered. I confused the Cloudfront cache issue with the docs not being updated properly. Closing this now.
