### ISSUE TITLE
FAQ / help docs typos

### ISSUE THREAD

**Issue by BassBauman** [MARKETProtocol/docs#60]
#### Describe the bug

**In the introduction:**

"Welcome to MARKET Protocol documentation here you will find documentation for our smart contracts and APIs." -> "Welcome to the MARKET Protocol documentation! Here you will find documentation for our smart contracts and APIs."

**In the Frequently Asked Questions section:** "General FAQ" and "MARKET Protocol FAQ" are duplicative and both link to the introduction.

**In the MPX section:** "For interacting with MPX, you will need to use a browser that supports Web3." -> "**_To interact_** with MPX, you will need to use a browser that supports Web3."

**In the Contributing section:**

"There are many ways to help, from reporting issues, contributing code, and helping us improve our community." -> "There are many ways to help, from reporting issues, contributing code, _**to**_ helping us improve our community."

"Please, start reading about our:" -> "**_Please start by_** reading about our:"

**In Gitcoin and Bounties section:**

"Please only 'start work' on an issue when your actually planning on working on it. Don't call dibs before you can allocate time to the issue" -> "Please only 'start work' on an issue when _**you are**_ actually planning on working on it. Don't call dibs before you can allocate time to the issue"

"Once you have create a PR, please submit work on Gitcoin so we are able to pay you out once we have accepted the work" -> "Once you have **_created_** a PR, please submit work on Gitcoin so we are able to pay you out once we have accepted the work"

**In Community Improvement:** "'general' channel on Discord" -> "#general channel on Discord" (to match earlier "#engineering Discord channel")

**Comment by rojosnow** [comment]
@BassBauman I think this covers your changes, http://dev.docs.marketprotocol.io.

**Comment by rojosnow** [comment]
Deployed to production
